### ISSUE TITLE
Poor documentation

### ISSUE THREAD

**Issue by AleCGames** [EvilMindDevs/com.solar2d-plugin.huaweiAdsKit#1]
Hi, i'm trying to include this plugin into my projects, but i can't see almost anything about the ads listener. I mean, there is no any info about the phases ('init', 'loaded', 'displayed', 'closed', 'reward', etc). Thank you for your contribution to the community.

**Comment by kayahanbaskeser** [comment]
Thanks for your comment, I will update the readme file as soon as possible.
